#Use this file to define directories within the project
#using the following format-> alias: path/to/file

#can then use the following line to import a .yml config file which will name all of
#our directories we might want to reference in the Gruntfile.js. Helps with
#maintenance.
#    var config = grunt.file.readYAML('Gruntconfig.yml');

